### ISSUE TITLE
Central: Add a PR check to run tests in dev

### ISSUE THREAD

**Issue by Linda-Vu** [Gary-Community-Ventures/benefits-calculator#1682]
### Context
To improve code quality and catch regressions early, we want to automate the process of running our Playwright end-to-end tests on every pull request. This will help ensure that new changes do not break existing user flows and that our application remains stable as we develop new features.

Currently, Playwright is configured in the repository, and there are existing test specs under the tests/ directory. However, these tests are not yet automatically executed as part of our pull request workflow.

### Dev Details
Set up a GitHub Actions workflow that is triggered whenever a pull request is opened or updated against the dev branch.

The workflow should:
1. Check out the repository code.
2. Set up Node.js (matching the project’s version in .nvmrc or package.json).
3. Install dependencies using npm ci.
4. Install Playwright browsers: npx playwright install --with-deps.
5. Run Playwright tests: npx playwright test.

The workflow should fail if any Playwright tests fail, blocking the PR from being merged until the issues are resolved.
Place the workflow file in .github/workflows/, e.g., .github/workflows/playwright.yml.
Example Workflow Snippet

```
yaml
CopyInsert
name: Playwright Tests

on:
  pull_request:
    branches: [dev]

jobs:
  test:
    runs-on: ubuntu-latest

steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18' # Update as needed
      - run: npm ci
      - run: npx playwright install --with-deps
      - run: npx playwright test
```
      
Update the Node.js version if your project requires a different one.
Test the workflow by opening a PR to dev and confirming that Playwright tests are executed.
